<?php
/**
 * Returns ['flag' => emoji, 'country' => name] for a given currency acronym.
 * Flags are generated at runtime via mb_chr() to avoid file-encoding issues
 * with multi-byte emoji on Windows/XAMPP environments.
 */
function getCurrencyMeta(string $acronym, string $lang = 'pt'): array
{
    static $meta = null;
    if ($meta === null) {

        // Generates a country-flag emoji from a 2-letter ISO 3166-1 alpha-2 code.
        // Regional Indicator base offset: 0x1F1A5
        $f = function (string $cc): string {
            return mb_chr(0x1F1A5 + ord($cc[0]), 'UTF-8')
                 . mb_chr(0x1F1A5 + ord($cc[1]), 'UTF-8');
        };

        // Special-purpose emoji for non-country currencies
        $earth  = mb_chr(0x1F30D, 'UTF-8'); // globe Africa/Europe
        $globe  = mb_chr(0x1F310, 'UTF-8'); // globe with meridians
        $island = mb_chr(0x1F3DD, 'UTF-8') . mb_chr(0xFE0F, 'UTF-8'); // desert island
        $gold_m = mb_chr(0x1F947, 'UTF-8'); // gold medal
        $silver = mb_chr(0x1F948, 'UTF-8'); // silver medal
        $gear   = mb_chr(0x2699,  'UTF-8') . mb_chr(0xFE0F, 'UTF-8'); // gear
        $btc    = mb_chr(0x20BF,  'UTF-8'); // Bitcoin sign

        // [flag, country_en, country_pt]
        $meta = [
            'AED' => [$f('AE'), 'UAE',            'Emirados'],
            'AFN' => [$f('AF'), 'Afghanistan',    'Afeganistão'],
            'ALL' => [$f('AL'), 'Albania',        'Albânia'],
            'AMD' => [$f('AM'), 'Armenia',        'Armênia'],
            'ANG' => [$island,  'Antilles',       'Antilhas'],
            'AOA' => [$f('AO'), 'Angola',         'Angola'],
            'ARS' => [$f('AR'), 'Argentina',      'Argentina'],
            'AUD' => [$f('AU'), 'Australia',      'Austrália'],
            'AWG' => [$f('AW'), 'Aruba',          'Aruba'],
            'AZN' => [$f('AZ'), 'Azerbaijan',     'Azerbaijão'],
            'BAM' => [$f('BA'), 'Bosnia',         'Bósnia'],
            'BBD' => [$f('BB'), 'Barbados',       'Barbados'],
            'BDT' => [$f('BD'), 'Bangladesh',     'Bangladesh'],
            'BGN' => [$f('BG'), 'Bulgaria',       'Bulgária'],
            'BHD' => [$f('BH'), 'Bahrain',        'Bahrein'],
            'BIF' => [$f('BI'), 'Burundi',        'Burundi'],
            'BMD' => [$f('BM'), 'Bermuda',        'Bermuda'],
            'BND' => [$f('BN'), 'Brunei',         'Brunei'],
            'BOB' => [$f('BO'), 'Bolivia',        'Bolívia'],
            'BRL' => [$f('BR'), 'Brazil',         'Brasil'],
            'BSD' => [$f('BS'), 'Bahamas',        'Bahamas'],
            'BTC' => [$btc,     'Bitcoin',        'Bitcoin'],
            'BTN' => [$f('BT'), 'Bhutan',         'Butão'],
            'BWP' => [$f('BW'), 'Botswana',       'Botsuana'],
            'BYN' => [$f('BY'), 'Belarus',        'Bielorrússia'],
            'BZD' => [$f('BZ'), 'Belize',         'Belize'],
            'CAD' => [$f('CA'), 'Canada',         'Canadá'],
            'CDF' => [$f('CD'), 'DR Congo',       'Congo RD'],
            'CHF' => [$f('CH'), 'Switzerland',    'Suíça'],
            'CLF' => [$f('CL'), 'Chile',          'Chile'],
            'CLP' => [$f('CL'), 'Chile',          'Chile'],
            'CNH' => [$f('CN'), 'China',          'China'],
            'CNY' => [$f('CN'), 'China',          'China'],
            'COP' => [$f('CO'), 'Colombia',       'Colômbia'],
            'CRC' => [$f('CR'), 'Costa Rica',     'Costa Rica'],
            'CUC' => [$f('CU'), 'Cuba',           'Cuba'],
            'CUP' => [$f('CU'), 'Cuba',           'Cuba'],
            'CVE' => [$f('CV'), 'Cape Verde',     'Cabo Verde'],
            'CZK' => [$f('CZ'), 'Czech Rep.',     'Rep. Tcheca'],
            'DJF' => [$f('DJ'), 'Djibouti',       'Djibuti'],
            'DKK' => [$f('DK'), 'Denmark',        'Dinamarca'],
            'DOP' => [$f('DO'), 'Dom. Republic',  'Rep. Dom.'],
            'DZD' => [$f('DZ'), 'Algeria',        'Argélia'],
            'EGP' => [$f('EG'), 'Egypt',          'Egito'],
            'ERN' => [$f('ER'), 'Eritrea',        'Eritreia'],
            'ETB' => [$f('ET'), 'Ethiopia',       'Etiópia'],
            'EUR' => [$f('EU'), 'Europe',         'Europa'],
            'FJD' => [$f('FJ'), 'Fiji',           'Fiji'],
            'FKP' => [$f('FK'), 'Falklands',      'Malvinas'],
            'GBP' => [$f('GB'), 'UK',             'Reino Unido'],
            'GEL' => [$f('GE'), 'Georgia',        'Geórgia'],
            'GGP' => [$f('GG'), 'Guernsey',       'Guernsey'],
            'GHS' => [$f('GH'), 'Ghana',          'Gana'],
            'GIP' => [$f('GI'), 'Gibraltar',      'Gibraltar'],
            'GMD' => [$f('GM'), 'Gambia',         'Gâmbia'],
            'GNF' => [$f('GN'), 'Guinea',         'Guiné'],
            'GTQ' => [$f('GT'), 'Guatemala',      'Guatemala'],
            'GYD' => [$f('GY'), 'Guyana',         'Guiana'],
            'HKD' => [$f('HK'), 'Hong Kong',      'Hong Kong'],
            'HNL' => [$f('HN'), 'Honduras',       'Honduras'],
            'HRK' => [$f('HR'), 'Croatia',        'Croácia'],
            'HTG' => [$f('HT'), 'Haiti',          'Haiti'],
            'HUF' => [$f('HU'), 'Hungary',        'Hungria'],
            'IDR' => [$f('ID'), 'Indonesia',      'Indonésia'],
            'ILS' => [$f('IL'), 'Israel',         'Israel'],
            'IMP' => [$f('IM'), 'Isle of Man',    'Ilha de Man'],
            'INR' => [$f('IN'), 'India',          'Índia'],
            'IQD' => [$f('IQ'), 'Iraq',           'Iraque'],
            'IRR' => [$f('IR'), 'Iran',           'Irã'],
            'ISK' => [$f('IS'), 'Iceland',        'Islândia'],
            'JEP' => [$f('JE'), 'Jersey',         'Jersey'],
            'JMD' => [$f('JM'), 'Jamaica',        'Jamaica'],
            'JOD' => [$f('JO'), 'Jordan',         'Jordânia'],
            'JPY' => [$f('JP'), 'Japan',          'Japão'],
            'KES' => [$f('KE'), 'Kenya',          'Quênia'],
            'KGS' => [$f('KG'), 'Kyrgyzstan',     'Quirguistão'],
            'KHR' => [$f('KH'), 'Cambodia',       'Camboja'],
            'KMF' => [$f('KM'), 'Comoros',        'Comores'],
            'KPW' => [$f('KP'), 'N. Korea',       'Coreia do N.'],
            'KRW' => [$f('KR'), 'S. Korea',       'Coreia do S.'],
            'KWD' => [$f('KW'), 'Kuwait',         'Kuwait'],
            'KYD' => [$f('KY'), 'Cayman Is.',     'Ilhas Cayman'],
            'KZT' => [$f('KZ'), 'Kazakhstan',     'Cazaquistão'],
            'LAK' => [$f('LA'), 'Laos',           'Laos'],
            'LBP' => [$f('LB'), 'Lebanon',        'Líbano'],
            'LKR' => [$f('LK'), 'Sri Lanka',      'Sri Lanka'],
            'LRD' => [$f('LR'), 'Liberia',        'Libéria'],
            'LSL' => [$f('LS'), 'Lesotho',        'Lesoto'],
            'LYD' => [$f('LY'), 'Libya',          'Líbia'],
            'MAD' => [$f('MA'), 'Morocco',        'Marrocos'],
            'MDL' => [$f('MD'), 'Moldova',        'Moldávia'],
            'MGA' => [$f('MG'), 'Madagascar',     'Madagascar'],
            'MKD' => [$f('MK'), 'N. Macedonia',   'Macedônia'],
            'MMK' => [$f('MM'), 'Myanmar',        'Mianmar'],
            'MNT' => [$f('MN'), 'Mongolia',       'Mongólia'],
            'MOP' => [$f('MO'), 'Macau',          'Macau'],
            'MRU' => [$f('MR'), 'Mauritania',     'Mauritânia'],
            'MUR' => [$f('MU'), 'Mauritius',      'Maurício'],
            'MVR' => [$f('MV'), 'Maldives',       'Maldivas'],
            'MWK' => [$f('MW'), 'Malawi',         'Malawi'],
            'MXN' => [$f('MX'), 'Mexico',         'México'],
            'MYR' => [$f('MY'), 'Malaysia',       'Malásia'],
            'MZN' => [$f('MZ'), 'Mozambique',     'Moçambique'],
            'NAD' => [$f('NA'), 'Namibia',        'Namíbia'],
            'NGN' => [$f('NG'), 'Nigeria',        'Nigéria'],
            'NIO' => [$f('NI'), 'Nicaragua',      'Nicarágua'],
            'NOK' => [$f('NO'), 'Norway',         'Noruega'],
            'NPR' => [$f('NP'), 'Nepal',          'Nepal'],
            'NZD' => [$f('NZ'), 'New Zealand',    'Nova Zelândia'],
            'OMR' => [$f('OM'), 'Oman',           'Omã'],
            'PAB' => [$f('PA'), 'Panama',         'Panamá'],
            'PEN' => [$f('PE'), 'Peru',           'Peru'],
            'PGK' => [$f('PG'), 'Papua N.G.',     'Papua N.G.'],
            'PHP' => [$f('PH'), 'Philippines',    'Filipinas'],
            'PKR' => [$f('PK'), 'Pakistan',       'Paquistão'],
            'PLN' => [$f('PL'), 'Poland',         'Polônia'],
            'PYG' => [$f('PY'), 'Paraguay',       'Paraguai'],
            'QAR' => [$f('QA'), 'Qatar',          'Catar'],
            'RON' => [$f('RO'), 'Romania',        'Romênia'],
            'RSD' => [$f('RS'), 'Serbia',         'Sérvia'],
            'RUB' => [$f('RU'), 'Russia',         'Rússia'],
            'RWF' => [$f('RW'), 'Rwanda',         'Ruanda'],
            'SAR' => [$f('SA'), 'Saudi Arabia',   'Arábia Saudita'],
            'SBD' => [$f('SB'), 'Solomon Is.',    'I. Salomão'],
            'SCR' => [$f('SC'), 'Seychelles',     'Seychelles'],
            'SDG' => [$f('SD'), 'Sudan',          'Sudão'],
            'SEK' => [$f('SE'), 'Sweden',         'Suécia'],
            'SGD' => [$f('SG'), 'Singapore',      'Singapura'],
            'SHP' => [$f('SH'), 'St. Helena',     'Santa Helena'],
            'SLE' => [$f('SL'), 'Sierra Leone',   'Serra Leoa'],
            'SLL' => [$f('SL'), 'Sierra Leone',   'Serra Leoa'],
            'SOS' => [$f('SO'), 'Somalia',        'Somália'],
            'SRD' => [$f('SR'), 'Suriname',       'Suriname'],
            'SSP' => [$f('SS'), 'S. Sudan',       'Sudão do Sul'],
            'STD' => [$f('ST'), 'São Tomé',       'São Tomé'],
            'STN' => [$f('ST'), 'São Tomé',       'São Tomé'],
            'SVC' => [$f('SV'), 'El Salvador',    'El Salvador'],
            'SYP' => [$f('SY'), 'Syria',          'Síria'],
            'SZL' => [$f('SZ'), 'Eswatini',       'Essuatíni'],
            'THB' => [$f('TH'), 'Thailand',       'Tailândia'],
            'TJS' => [$f('TJ'), 'Tajikistan',     'Tajiquistão'],
            'TMT' => [$f('TM'), 'Turkmenistan',   'Turcomenistão'],
            'TND' => [$f('TN'), 'Tunisia',        'Tunísia'],
            'TOP' => [$f('TO'), 'Tonga',          'Tonga'],
            'TRY' => [$f('TR'), 'Turkey',         'Turquia'],
            'TTD' => [$f('TT'), 'Trinidad',       'Trinidad'],
            'TWD' => [$f('TW'), 'Taiwan',         'Taiwan'],
            'TZS' => [$f('TZ'), 'Tanzania',       'Tanzânia'],
            'UAH' => [$f('UA'), 'Ukraine',        'Ucrânia'],
            'UGX' => [$f('UG'), 'Uganda',         'Uganda'],
            'USD' => [$f('US'), 'USA',            'EUA'],
            'UYU' => [$f('UY'), 'Uruguay',        'Uruguai'],
            'UZS' => [$f('UZ'), 'Uzbekistan',     'Uzbequistão'],
            'VES' => [$f('VE'), 'Venezuela',      'Venezuela'],
            'VND' => [$f('VN'), 'Vietnam',        'Vietnã'],
            'VUV' => [$f('VU'), 'Vanuatu',        'Vanuatu'],
            'WST' => [$f('WS'), 'Samoa',          'Samoa'],
            'XAF' => [$earth,   'Central Africa', 'África Central'],
            'XAG' => [$silver,  'Silver',         'Prata'],
            'XAU' => [$gold_m,  'Gold',           'Ouro'],
            'XCD' => [$island,  'E. Caribbean',   'Caribe Leste'],
            'XCG' => [$island,  'Caribbean',      'Caribe'],
            'XDR' => [$globe,   'IMF',            'FMI'],
            'XOF' => [$earth,   'West Africa',    'África Ocid.'],
            'XPD' => [$gear,    'Palladium',      'Paládio'],
            'XPF' => [$f('PF'), 'Fr. Polynesia',  'Pol. Francesa'],
            'XPT' => [$gear,    'Platinum',       'Platina'],
            'YER' => [$f('YE'), 'Yemen',          'Iêmen'],
            'ZAR' => [$f('ZA'), 'South Africa',   'África do Sul'],
            'ZMW' => [$f('ZM'), 'Zambia',         'Zâmbia'],
            'ZWG' => [$f('ZW'), 'Zimbabwe',       'Zimbábue'],
            'ZWL' => [$f('ZW'), 'Zimbabwe',       'Zimbábue'],
        ];
    }

    $entry = $meta[$acronym] ?? [mb_chr(0x1F3E6, 'UTF-8'), $acronym, $acronym]; // 🏦 fallback
    return [
        'flag'    => $entry[0],
        'country' => $lang === 'en' ? $entry[1] : $entry[2],
    ];
}
