<?php
$translations = [
    'en' => [
        'site_name'           => 'Am I A Millionaire?',
        'tagline'             => 'Discover in how many world currencies you\'re already a millionaire',
        'meta_desc_home'      => 'Find out in how many of the 170+ world currencies you are a millionaire. Track your savings and get motivated to grow your wealth.',
        'meta_desc_login'     => 'Sign in to Am I A Millionaire? and check your millionaire status across 170+ world currencies.',
        'meta_desc_register'  => 'Create your free account and discover in how many world currencies you are already a millionaire.',
        'meta_desc_dash'      => 'Your millionaire dashboard. See which currencies you\'ve conquered and how close you are to the next milestone.',
        'meta_desc_update'    => 'Update your savings balance and currency to keep your millionaire status accurate.',
        // Nav
        'nav_update'          => 'Update',
        'nav_logout'          => 'Logout',
        'nav_delete'          => 'Delete',
        // Login
        'login_title'         => 'Welcome Back!',
        'login_subtitle'      => 'Sign in to check your millionaire status',
        'login_email'         => 'Email address',
        'login_password'      => 'Password',
        'login_btn'           => 'PASS GO →',
        'login_no_account'    => "Don't have an account?",
        'login_register'      => 'Register here',
        'login_success'       => 'Login successful! Redirecting...',
        'login_error'         => 'Invalid email or password. Please try again.',
        // Register
        'reg_title'           => 'Start Your Journey',
        'reg_subtitle'        => 'Create your account and discover your millionaire status',
        'reg_name'            => 'Full name',
        'reg_email'           => 'Email address',
        'reg_password'        => 'Password',
        'reg_confirm'         => 'Confirm password',
        'reg_currency'        => 'Your savings currency',
        'reg_amount'          => 'Current savings amount',
        'reg_amount_hint'     => 'How much do you have saved right now?',
        'reg_btn'             => 'CREATE ACCOUNT',
        'reg_has_account'     => 'Already have an account?',
        'reg_login'           => 'Sign in here',
        'reg_success'         => 'Account created! Redirecting to login...',
        'reg_email_exists'    => 'This email is already registered. Please use another.',
        'reg_pass_mismatch'   => 'Passwords do not match.',
        // Dashboard
        'dash_welcome'        => 'Welcome back',
        'dash_balance'        => 'Your Balance',
        'dash_millionaire_in' => "You're a millionaire in",
        'dash_currencies'     => 'currencies',
        'dash_currency'       => 'currency',
        'dash_next_goal'      => 'NEXT MILESTONE',
        'dash_missing'        => 'more to reach 1,000,000',
        'dash_in'             => 'in',
        'dash_conquered'      => 'Conquered Currencies',
        'dash_yes'            => 'MILLIONAIRE',
        'dash_updated'        => 'Rates updated',
        'dash_no_million'     => "Keep saving! You're not yet a millionaire in any currency.",
        'dash_tip'            => 'The more you save, the more currencies you conquer!',
        'dash_rank_0'         => 'Beginner Saver',
        'dash_rank_1'         => 'Junior Millionaire',
        'dash_rank_2'         => 'Global Millionaire',
        'dash_rank_3'         => 'Mega Millionaire',
        'dash_rank_4'         => 'Ultra Millionaire',
        // Update
        'upd_title'           => 'Update Savings',
        'upd_subtitle'        => 'Keep your balance up to date',
        'upd_currency'        => 'Currency',
        'upd_amount'          => 'Amount',
        'upd_btn'             => 'UPDATE →',
        'upd_current'         => 'Current balance',
        // Delete
        'del_title'           => 'Delete Account',
        'del_warning'         => 'This action is irreversible. All your data will be permanently deleted.',
        'del_password'        => 'Enter your password to confirm',
        'del_btn'             => 'DELETE MY ACCOUNT',
        'del_back'            => '← Go back',
        'del_success'         => 'Account deleted. Redirecting...',
        'del_error'           => 'Incorrect password. Please try again.',
        // Landing
        'land_hero'           => 'Are you a millionaire?',
        'land_subhero'        => "Discover in how many of the world's 170+ currencies you already have 1,000,000 or more.",
        'land_cta'            => 'CHECK NOW — FREE',
        'land_login'          => 'Already have an account? Sign in',
        'land_how_title'      => 'How it works',
        'land_step1_title'    => 'Enter your savings',
        'land_step1_desc'     => 'Tell us how much you have saved and in which currency.',
        'land_step2_title'    => 'We do the math',
        'land_step2_desc'     => 'We convert your balance to 170+ world currencies using live exchange rates.',
        'land_step3_title'    => 'See your status',
        'land_step3_desc'     => 'Discover where you\'re already a millionaire and your next financial milestone.',
        'land_why_title'      => 'Why track your millionaire status?',
        'land_why_desc'       => 'Building a financial reserve is a long journey. Seeing that you\'re already a millionaire in dozens of currencies keeps you motivated to save more and reach the next milestone.',
        // Converter (public)
        'conv_hero_title'     => 'Are you a millionaire?',
        'conv_hero_sub'       => "Enter your savings below and discover in how many of the world's 170+ currencies you already have 1,000,000 or more.",
        'conv_amount'         => 'Your savings amount',
        'conv_currency'       => 'Currency',
        'conv_btn'            => 'CHECK NOW →',
        'conv_result_in'      => "You're a millionaire in",
        'conv_next'           => 'Next milestone',
        'conv_conquered'      => 'Conquered Currencies',
        'conv_save_title'     => 'Save your progress!',
        'conv_save_desc'      => 'Create a free account to track your savings over time and watch yourself conquer more and more currencies.',
        'conv_save_btn'       => 'CREATE FREE ACCOUNT',
        'conv_login_link'     => 'Already have an account? Sign in',
        'conv_how_title'      => 'How does it work?',
        'conv_badge'          => 'MILLIONAIRE',
        'badge_billion'       => 'BILLIONAIRE',
        'conv_try_demo'       => 'Try with your own savings',
        'footer_copy'         => '© 2026 Am I A Millionaire? All rights reserved. Created by Lennon Sales Furtado. Contact me - lennonsfurtado@gmail.com',
    ],
    'pt' => [
        'site_name'           => 'Sou Milionário?',
        'tagline'             => 'Descubra em quantas moedas do mundo você já é milionário',
        'meta_desc_home'      => 'Descubra em quantas das 170+ moedas do mundo você é milionário. Acompanhe suas economias e se motive a crescer sua reserva financeira.',
        'meta_desc_login'     => 'Entre no Sou Milionário? e verifique seu status de milionário em mais de 170 moedas do mundo.',
        'meta_desc_register'  => 'Crie sua conta gratuita e descubra em quantas moedas do mundo você já é milionário.',
        'meta_desc_dash'      => 'Seu painel de milionário. Veja quais moedas você já conquistou e quanto falta para a próxima meta.',
        'meta_desc_update'    => 'Atualize o valor da sua reserva e a moeda para manter seu status de milionário preciso.',
        // Nav
        'nav_update'          => 'Atualizar',
        'nav_logout'          => 'Sair',
        'nav_delete'          => 'Apagar',
        // Login
        'login_title'         => 'Bem-vindo de volta!',
        'login_subtitle'      => 'Entre para ver seu status de milionário',
        'login_email'         => 'E-mail',
        'login_password'      => 'Senha',
        'login_btn'           => 'ENTRAR →',
        'login_no_account'    => 'Não tem uma conta?',
        'login_register'      => 'Cadastre-se aqui',
        'login_success'       => 'Login realizado! Redirecionando...',
        'login_error'         => 'E-mail ou senha inválidos. Tente novamente.',
        // Register
        'reg_title'           => 'Comece sua Jornada',
        'reg_subtitle'        => 'Crie sua conta e descubra seu status de milionário',
        'reg_name'            => 'Nome completo',
        'reg_email'           => 'E-mail',
        'reg_password'        => 'Senha',
        'reg_confirm'         => 'Confirmar senha',
        'reg_currency'        => 'Moeda da sua reserva',
        'reg_amount'          => 'Valor atual da reserva',
        'reg_amount_hint'     => 'Quanto você tem guardado agora?',
        'reg_btn'             => 'CRIAR CONTA',
        'reg_has_account'     => 'Já tem uma conta?',
        'reg_login'           => 'Entre aqui',
        'reg_success'         => 'Conta criada! Redirecionando para o login...',
        'reg_email_exists'    => 'Este e-mail já está cadastrado. Tente outro.',
        'reg_pass_mismatch'   => 'As senhas não coincidem.',
        // Dashboard
        'dash_welcome'        => 'Bem-vindo',
        'dash_balance'        => 'Sua Reserva',
        'dash_millionaire_in' => 'Você é milionário em',
        'dash_currencies'     => 'moedas',
        'dash_currency'       => 'moeda',
        'dash_next_goal'      => 'PRÓXIMA META',
        'dash_missing'        => 'faltam para 1.000.000',
        'dash_in'             => 'em',
        'dash_conquered'      => 'Moedas Conquistadas',
        'dash_yes'            => 'MILIONÁRIO',
        'dash_updated'        => 'Câmbio atualizado',
        'dash_no_million'     => 'Continue economizando! Você ainda não é milionário em nenhuma moeda.',
        'dash_tip'            => 'Quanto mais você economiza, mais moedas você conquista!',
        'dash_rank_0'         => 'Poupador Iniciante',
        'dash_rank_1'         => 'Milionário Júnior',
        'dash_rank_2'         => 'Milionário Global',
        'dash_rank_3'         => 'Mega Milionário',
        'dash_rank_4'         => 'Ultra Milionário',
        // Update
        'upd_title'           => 'Atualizar Reserva',
        'upd_subtitle'        => 'Mantenha seu saldo sempre atualizado',
        'upd_currency'        => 'Moeda',
        'upd_amount'          => 'Valor',
        'upd_btn'             => 'ATUALIZAR →',
        'upd_current'         => 'Saldo atual',
        // Delete
        'del_title'           => 'Apagar Conta',
        'del_warning'         => 'Esta ação é irreversível. Todos os seus dados serão permanentemente excluídos.',
        'del_password'        => 'Digite sua senha para confirmar',
        'del_btn'             => 'APAGAR MINHA CONTA',
        'del_back'            => '← Voltar',
        'del_success'         => 'Conta apagada. Redirecionando...',
        'del_error'           => 'Senha incorreta. Tente novamente.',
        // Landing
        'land_hero'           => 'Você é milionário?',
        'land_subhero'        => 'Descubra em quantas das 170+ moedas do mundo você já tem 1.000.000 ou mais.',
        'land_cta'            => 'VERIFICAR AGORA — GRATUITO',
        'land_login'          => 'Já tem uma conta? Entre aqui',
        'land_how_title'      => 'Como funciona',
        'land_step1_title'    => 'Informe sua reserva',
        'land_step1_desc'     => 'Diga quanto você tem guardado e em qual moeda.',
        'land_step2_title'    => 'Fazemos os cálculos',
        'land_step2_desc'     => 'Convertemos sua reserva para mais de 170 moedas usando câmbio em tempo real.',
        'land_step3_title'    => 'Veja seu status',
        'land_step3_desc'     => 'Descubra onde você já é milionário e sua próxima meta financeira.',
        'land_why_title'      => 'Por que acompanhar seu status de milionário?',
        'land_why_desc'       => 'Construir uma reserva financeira é uma jornada longa. Ver que você já é milionário em dezenas de moedas te mantém motivado a economizar mais e alcançar a próxima meta.',
        // Converter (public)
        'conv_hero_title'     => 'Você é milionário?',
        'conv_hero_sub'       => 'Insira sua reserva abaixo e descubra em quantas das 170+ moedas do mundo você já tem 1.000.000 ou mais.',
        'conv_amount'         => 'Valor da sua reserva',
        'conv_currency'       => 'Moeda',
        'conv_btn'            => 'VERIFICAR AGORA →',
        'conv_result_in'      => 'Você é milionário em',
        'conv_next'           => 'Próxima meta',
        'conv_conquered'      => 'Moedas Conquistadas',
        'conv_save_title'     => 'Salve seu progresso!',
        'conv_save_desc'      => 'Crie uma conta gratuita para acompanhar sua reserva ao longo do tempo e ver conforme você conquista cada vez mais moedas.',
        'conv_save_btn'       => 'CRIAR CONTA GRATUITA',
        'conv_login_link'     => 'Já tem uma conta? Entre aqui',
        'conv_how_title'      => 'Como funciona?',
        'conv_badge'          => 'MILIONÁRIO',
        'badge_billion'       => 'BILIONÁRIO',
        'conv_try_demo'       => 'Experimente com sua reserva',
        'footer_copy'         => '© 2026 Sou Milionário? Todos os direitos reservados. Criado por Lennon Sales Furtado. Fale comigo - lennonsfurtado@gmail.com',
    ],
];

$t = $translations[$lang];
